language: go
branches:
  only:
  - master
  - v0
sudo: false
before_install:
- make tools
- go get -t ./...
script:
- make check
- make test
- make build
after_success:
- make coveralls
notifications:
  email: false
